name: Basic CI Example # GitHub Actions 탭에 표시될 이름입니다.

on:
  push:
    branches: [ "main" ] # main 브랜치에 푸시될 때 실행
  pull_request:
    branches: [ "main" ] # main 브랜치로 PR이 생성될 때 실행
    
jobs:
  build:
    runs-on: ubuntu-latest # 가상 머신 OS 환경 (우분투)
    
    steps:
    - name: Checkout repository code # 1. 저장소의 코드를 가상 머신으로 가져오기
      uses: actions/checkout@v4
      
    - name: Run a one-line script # 2. 화면에 메세지 출력하기
      run: echo "Hello, GitHub Actions! 환경 설정이 완료되었습니다."
      
    - name: Set up Python # 3. 파이썬 설치 (Action 활용)
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Display Python version # 4. 설치된 파이썬 버전 확인
      run: python --version